# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_camera_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(741, 532)
        MainWindow.setStyleSheet("background-color:rgb(17, 25, 31)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Header = QtWidgets.QFrame(self.centralwidget)
        self.Header.setStyleSheet("color: rgb(245, 245, 245);")
        self.Header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header.setObjectName("Header")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.Header)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.left_header = QtWidgets.QFrame(self.Header)
        self.left_header.setStyleSheet("color: rgb(187, 198, 206);")
        self.left_header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_header.setObjectName("left_header")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.left_header)
        self.horizontalLayout_7.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.left_header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(50, 50))
        self.label_2.setMidLineWidth(0)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/source/cam logo 1.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.left_header)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("margin: 5px;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_11.addWidget(self.left_header)
        self.right_header = QtWidgets.QFrame(self.Header)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.right_header.setFont(font)
        self.right_header.setStyleSheet("QPushButton {\n"
"  margin-right: 10px; /* Adjust the value as needed */\n"
"  padding: 5px 10px; /* Adjust the value as needed */\n"
"}\n"
"")
        self.right_header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_header.setObjectName("right_header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.right_header)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.home = QtWidgets.QPushButton(self.right_header)
        self.home.setStyleSheet("QPushButton {\n"
"    background-color: rgb(101, 144, 161);\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(90, 128, 143);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(90, 128, 143);\n"
"}")
        self.home.setObjectName("home")
        self.horizontalLayout.addWidget(self.home)
        self.camera = QtWidgets.QPushButton(self.right_header)
        self.camera.setStyleSheet("QPushButton {\n"
"    background-color: rgb(101, 144, 161);\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(90, 128, 143);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(90, 128, 143);\n"
"}")
        self.camera.setObjectName("camera")
        self.horizontalLayout.addWidget(self.camera)
        self.person = QtWidgets.QPushButton(self.right_header)
        self.person.setStyleSheet("QPushButton {\n"
"    background-color: rgb(101, 144, 161);\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding:10px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(90, 128, 143);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(90, 128, 143);\n"
"}")
        self.person.setObjectName("person")
        self.horizontalLayout.addWidget(self.person)
        self.List = QtWidgets.QPushButton(self.right_header)
        self.List.setStyleSheet("QPushButton {\n"
"    background-color: rgb(101, 144, 161);\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding:10px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(90, 128, 143);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(90, 128, 143);\n"
"}")
        self.List.setObjectName("List")
        self.horizontalLayout.addWidget(self.List)
        self.log = QtWidgets.QPushButton(self.right_header)
        self.log.setStyleSheet("QPushButton {\n"
"    background-color: rgb(101, 144, 161);\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding:10px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(90, 128, 143);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(90, 128, 143);\n"
"}")
        self.log.setObjectName("log")
        self.horizontalLayout.addWidget(self.log)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_11.addWidget(self.right_header)
        self.verticalLayout.addWidget(self.Header)
        self.Main = QtWidgets.QFrame(self.centralwidget)
        self.Main.setStyleSheet("")
        self.Main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Main.setObjectName("Main")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.Main)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.Main)
        self.label_10.setMinimumSize(QtCore.QSize(150, 20))
        self.label_10.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("\n"
"color: rgb(225, 230, 235);")
        self.label_10.setScaledContents(False)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.Main)
        self.label_11.setMinimumSize(QtCore.QSize(270, 15))
        self.label_11.setMaximumSize(QtCore.QSize(270, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color:rgb(115, 130, 140);")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.horizontalLayout_8.addLayout(self.verticalLayout_2)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_8)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem4 = QtWidgets.QSpacerItem(98, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.frame = QtWidgets.QFrame(self.Main)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame.setFont(font)
        self.frame.setStyleSheet("QLineEdit {\n"
"                background-color: transparent;\n"
"                border: 1px solid #4e4e50;\n"
"                border-radius: 15px;\n"
"                color: #e6e6e6;\n"
"               padding: 5px 10px;\n"
"                margin: 5px 0\n"
"            }\n"
"            QLineEdit:focus {\n"
"                border-color: #3282b8;\n"
"            }\n"
"QTextEdit {\n"
"                background-color: transparent;\n"
"                border: 1px solid #4e4e50;\n"
"                border-radius: 15px;\n"
"                color: #e6e6e6;\n"
"                padding: 5px 10px;\n"
"                margin: 5px 0\n"
"            }\n"
"            QTextEdit:focus {\n"
"                border-color: #3282b8;\n"
"            }")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.CameraName = QtWidgets.QLineEdit(self.frame)
        self.CameraName.setMinimumSize(QtCore.QSize(300, 60))
        self.CameraName.setMaximumSize(QtCore.QSize(300, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.CameraName.setFont(font)
        self.CameraName.setObjectName("CameraName")
        self.verticalLayout_3.addWidget(self.CameraName)
        self.IPAddress = QtWidgets.QLineEdit(self.frame)
        self.IPAddress.setMinimumSize(QtCore.QSize(300, 60))
        self.IPAddress.setMaximumSize(QtCore.QSize(300, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.IPAddress.setFont(font)
        self.IPAddress.setStyleSheet("")
        self.IPAddress.setText("")
        self.IPAddress.setObjectName("IPAddress")
        self.verticalLayout_3.addWidget(self.IPAddress)
        self.Location = QtWidgets.QTextEdit(self.frame)
        self.Location.setMinimumSize(QtCore.QSize(300, 100))
        self.Location.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Location.setFont(font)
        self.Location.setObjectName("Location")
        self.verticalLayout_3.addWidget(self.Location)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem5)
        self.Save = QtWidgets.QPushButton(self.frame)
        self.Save.setMinimumSize(QtCore.QSize(180, 50))
        self.Save.setMaximumSize(QtCore.QSize(170, 70))
        self.Save.setStyleSheet("QPushButton {\n"
"    background-color: rgb(101, 144, 161);\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"margin: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(90, 128, 143);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(90, 128, 143);\n"
"}")
        self.Save.setObjectName("Save")
        self.horizontalLayout_13.addWidget(self.Save)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_9.addWidget(self.frame)
        spacerItem7 = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        spacerItem8 = QtWidgets.QSpacerItem(17, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem8)
        self.horizontalLayout_10.addLayout(self.verticalLayout_6)
        spacerItem9 = QtWidgets.QSpacerItem(20, 417, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.verticalLayout.addWidget(self.Main)
        self.footer = QtWidgets.QFrame(self.centralwidget)
        self.footer.setStyleSheet("color: rgb(187, 198, 206);")
        self.footer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer.setObjectName("footer")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.footer)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.left_footer_2 = QtWidgets.QFrame(self.footer)
        self.left_footer_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_footer_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_footer_2.setObjectName("left_footer_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.left_footer_2)
        self.horizontalLayout_5.setContentsMargins(5, 0, 0, 5)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.left_footer_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3.addWidget(self.left_footer_2, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout.addWidget(self.footer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "PERSON REID"))
        self.home.setText(_translate("MainWindow", "Home"))
        self.camera.setText(_translate("MainWindow", "Add Camera"))
        self.person.setText(_translate("MainWindow", "Search Person"))
        self.List.setText(_translate("MainWindow", "List User"))
        self.log.setText(_translate("MainWindow", "Logout"))
        self.label_10.setText(_translate("MainWindow", "Add new camera"))
        self.label_11.setText(_translate("MainWindow", "Enter specifications to integrate a new camera"))
        self.CameraName.setPlaceholderText(_translate("MainWindow", "Camera name"))
        self.IPAddress.setPlaceholderText(_translate("MainWindow", "IP address"))
        self.Location.setPlaceholderText(_translate("MainWindow", "Location"))
        self.Save.setText(_translate("MainWindow", "Save Configuration"))
        self.label.setText(_translate("MainWindow", "Version 1.0 | Copyright © ReID"))

import source


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
