# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search_Admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(831, 532)
        MainWindow.setStyleSheet("background-color:rgb(17, 25, 31)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Header = QtWidgets.QFrame(self.centralwidget)
        self.Header.setStyleSheet("color: rgb(245, 245, 245);")
        self.Header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header.setObjectName("Header")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.Header)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.left_header = QtWidgets.QFrame(self.Header)
        self.left_header.setStyleSheet("color: rgb(187, 198, 206);")
        self.left_header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_header.setObjectName("left_header")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.left_header)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(5, -1, -1, -1)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.left_header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMaximumSize(QtCore.QSize(50, 50))
        self.label_7.setMidLineWidth(0)
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/source/cam logo 1.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.label_3 = QtWidgets.QLabel(self.left_header)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("margin: 5px;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_11.addWidget(self.left_header)
        self.right_header = QtWidgets.QFrame(self.Header)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.right_header.setFont(font)
        self.right_header.setStyleSheet("QPushButton {\n"
"  margin-right: 10px; /* Adjust the value as needed */\n"
"  padding: 5px 10px; /* Adjust the value as needed */\n"
"}\n"
"")
        self.right_header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_header.setObjectName("right_header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.right_header)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.home = QtWidgets.QPushButton(self.right_header)
        self.home.setStyleSheet("QPushButton {\n"
"    background-color: rgb(101, 144, 161);\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(90, 128, 143);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(90, 128, 143);\n"
"}")
        self.home.setObjectName("home")
        self.horizontalLayout.addWidget(self.home)
        self.clicking = QtWidgets.QPushButton(self.right_header)
        self.clicking.setStyleSheet("QPushButton {\n"
"    background-color: rgb(101, 144, 161);\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(90, 128, 143);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(90, 128, 143);\n"
"}")
        self.clicking.setObjectName("clicking")
        self.horizontalLayout.addWidget(self.clicking)
        self.person = QtWidgets.QPushButton(self.right_header)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.person.setFont(font)
        self.person.setStyleSheet("QPushButton {\n"
"    background-color: rgb(101, 144, 161);\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding:10px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(90, 128, 143);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(90, 128, 143);\n"
"}")
        self.person.setObjectName("person")
        self.horizontalLayout.addWidget(self.person)
        self.pushButton_7 = QtWidgets.QPushButton(self.right_header)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background-color: rgb(101, 144, 161);\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding:10px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(90, 128, 143);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(90, 128, 143);\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout.addWidget(self.pushButton_7)
        self.pushButton_4 = QtWidgets.QPushButton(self.right_header)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: rgb(101, 144, 161);\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding:10px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(90, 128, 143);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(90, 128, 143);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_11.addWidget(self.right_header)
        self.verticalLayout.addWidget(self.Header)
        self.Main = QtWidgets.QFrame(self.centralwidget)
        self.Main.setStyleSheet("")
        self.Main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Main.setObjectName("Main")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.Main)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 417, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.horizontalLayout_12.addLayout(self.horizontalLayout_8)
        self.frame = QtWidgets.QFrame(self.Main)
        self.frame.setMinimumSize(QtCore.QSize(700, 350))
        self.frame.setMaximumSize(QtCore.QSize(700, 350))
        self.frame.setStyleSheet("background-color:rgb(20, 30, 38);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setMinimumSize(QtCore.QSize(170, 20))
        self.label_10.setMaximumSize(QtCore.QSize(170, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("margin-right: 10px;\n"
"color: rgb(225, 230, 235);")
        self.label_10.setScaledContents(False)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setMinimumSize(QtCore.QSize(300, 15))
        self.label_11.setMaximumSize(QtCore.QSize(300, 15))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color:rgb(115, 130, 140);\n"
"margin-right:10px;\n"
"")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, 15, -1, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_5.setMaximumSize(QtCore.QSize(100, 40))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: rgb(200, 215, 218);\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(90, 128, 143);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(90, 128, 143);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_9.addWidget(self.pushButton_5)
        self.label_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgb(115, 130, 140);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setMinimumSize(QtCore.QSize(200, 40))
        self.pushButton_6.setMaximumSize(QtCore.QSize(200, 40))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: rgb(101, 144, 161);\n"
"    color: white;\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(90, 128, 143);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(90, 128, 143);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_9.addWidget(self.pushButton_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setMinimumSize(QtCore.QSize(180, 150))
        self.label_5.setMaximumSize(QtCore.QSize(180, 150))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel {\n"
"                background-color: transparent;\n"
"                border: 1px solid #4e4e50;\n"
"                border-radius: 15px;\n"
"                color:rgb(170, 170, 170);\n"
"               padding: 5px 10px;\n"
"                margin: 5px 0;\n"
"qproperty-alignment: AlignCenter;\n"
"    \n"
"            }\n"
"            QLineEdit:focus {\n"
"                border-color: #3282b8;\n"
"            }")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_10.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgb(115, 130, 140);")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12.addWidget(self.frame)
        spacerItem3 = QtWidgets.QSpacerItem(34, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.Main)
        self.footer = QtWidgets.QFrame(self.centralwidget)
        self.footer.setStyleSheet("color: rgb(187, 198, 206);")
        self.footer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.footer.setObjectName("footer")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.footer)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.left_footer_2 = QtWidgets.QFrame(self.footer)
        self.left_footer_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_footer_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_footer_2.setObjectName("left_footer_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.left_footer_2)
        self.horizontalLayout_5.setContentsMargins(5, 0, 0, 5)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.left_footer_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3.addWidget(self.left_footer_2, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout.addWidget(self.footer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "PERSON REID"))
        self.home.setText(_translate("MainWindow", "Home"))
        self.clicking.setText(_translate("MainWindow", "Add Camera"))
        self.person.setText(_translate("MainWindow", "Search Person"))
        self.pushButton_7.setText(_translate("MainWindow", "List User"))
        self.pushButton_4.setText(_translate("MainWindow", "Logout"))
        self.label_10.setText(_translate("MainWindow", "Search for a person"))
        self.label_11.setText(_translate("MainWindow", "Upload a picture to search across camera feeds "))
        self.pushButton_5.setText(_translate("MainWindow", "Choose File"))
        self.label_4.setText(_translate("MainWindow", "No file chosen"))
        self.pushButton_6.setText(_translate("MainWindow", "Search"))
        self.label_5.setText(_translate("MainWindow", "Result"))
        self.label_6.setText(_translate("MainWindow", "Camera location"))
        self.label.setText(_translate("MainWindow", "Version 1.0 | Copyright © ReID"))

import source


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
